### ISSUE TITLE
Install Vault Pod

### ISSUE THREAD

**Issue by azaa1** [fscoding/main-fscoding#2]
- Install Vault Pod

We started running our application on k8s. We need to store creds somewhere so vault is the  best open source in our case  Please create vault server on namespace call vault-space

name: vault
port: 80
namespace: vault-space

Documentation: 

https://medium.com/@gmaliar/dynamic-secrets-on-kubernetes-pods-using-vault-35d9094d169

**Comment by NadiraSaip** [comment]
Please share with me your documentation for vault images

**Comment by SharifAbdulcoder** [comment]
> Please share with me your documentation for vault images
I do not have my own documentation however I've confirmed that dockerhub has all-ready 'vault' image, maybe that would be help to you. 
link: https://hub.docker.com/_/vault
