### ISSUE TITLE
Create docker register 

### ISSUE THREAD

**Issue by fsadykov** [fscoding/main-fscoding#7]
Please create docker register call fscoding. Make sure our nodes can push and pull from docker register. Please let me know if you have questions. Thank you 

https://cloud.google.com/container-registry/docs/pushing-and-pulling?hl=en_US&_ga=2.254437197.-47079899.1551903540

**Comment by SharifAbdulcoder** [comment]
Created Docker Registry 👍 
Instructions:

After you've created you're image from Dockerfile, give it a tag; 
sudo docker tag [IMAGE_NAME] gcr.io/fscoding/[IMAGE]

After tagging the image you've created, you are now able to push the image into Container Registry; 
sudo docker push gcr.io/fscoding/[IMAGE]
